name: build_deploy_aks
on:
  push:
    paths:
      - "azure-vote/**"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source code 
        uses: actions/checkout@v3

      # 🔹 Log in to Azure using service principal
      - name: Azure login
        uses: azure/login@v1.4.3
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      # 🔹 Log in to ACR
      - name: Docker login to ACR
        run: |
          az acr login --name ${{ secrets.registry }}

      # 🔹 Build and push Docker image
      - name: Build and Push Docker image
        run: |
          IMAGE_NAME=${{ secrets.registry }}.azurecr.io/${{ secrets.repository }}/azure-vote-front:${{ github.sha }}
          echo "Building and pushing image: $IMAGE_NAME"
          docker build -t $IMAGE_NAME ./azure-vote
          docker push $IMAGE_NAME

      # 🔹 Set AKS context
      - name: Set AKS context
        uses: azure/aks-set-context@v3
        with:
          resource-group: ${{ secrets.resource_group }}
          cluster-name: ${{ secrets.cluster_name }}

      # 🔹 Setup kubectl
      - name: Setup kubectl
        uses: azure/setup-kubectl@v3

      # 🔹 Deploy to AKS
      - name: Deploy to AKS
        uses: Azure/k8s-deploy@v4
        with:
          namespace: default
          manifests: |
            azure-vote-all-in-one-redis.yaml
          images: |
            ${{ secrets.registry }}.azurecr.io/${{ secrets.repository }}/azure-vote-front:${{ github.sha }}
          pull-images: false
